# supabase/config.toml

[functions.ping]
verify_jwt = false
import_map = "./functions/ping/import_map.json"
# entrypoint defaults to ./functions/ping/index.ts

[functions.hello]
verify_jwt = false
import_map = "./functions/hello/import_map.json"
# entrypoint defaults to ./functions/hello/index.ts