name: "Edge Functions: Deploy (prod)"

on:
  push:
    branches: [ "prod" ]
    paths:
      - "supabase/functions/**"
      - "supabase/config.toml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x
      - run: deno task test
      - run: deno task coverage

  deploy:
    needs: test
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Detect changed functions
        id: changed
        run: |
          git fetch origin ${{ github.event.before }}
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^supabase/functions/' | awk -F'/' '{print $3}' | sort | uniq)
          echo "changed_functions=$CHANGED" >> $GITHUB_OUTPUT
      - name: Deploy changed functions
        if: steps.changed.outputs.changed_functions != ''
        run: |
          for fn in ${{ steps.changed.outputs.changed_functions }}; do
            supabase functions deploy $fn --project-ref $SUPABASE_PROJECT_REF
          done