name: "Edge Functions: Deploy (prod)"

on:
  push:
    branches: [ "prod" ]
    paths:
      - "supabase/functions/**"
      - "supabase/config.toml"
      - "supabase/import_map.json"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase functions deploy --project-ref $SUPABASE_PROJECT_REF
